with cte as (
SELECT *, ROW_NUMBER() OVER (PARTITION BY dataset, processmonth ORDER BY date desc) AS row_number,
case
    when lower(dataset) like '%cmbs%'
        or lower(dataset) like '%rpt%'
        or lower(dataset) like '%loan%'
        or lower(dataset) like '%mdr%'
        or lower(dataset) like '%fha%'
        or lower(dataset) like '%fannie%'
        or lower(dataset) like '%property%'
        or lower(dataset) like '%deal%'
        or lower(dataset) like '%spatial%'
        or lower(dataset) like '%userperm%'
        or lower(dataset) like '%treppwebdb3%'
        or lower(dataset) like '%watchlistcommentaries%'
        or lower(dataset) like '%commentarywatchlist%'
        or lower(dataset) like '%archivedb%'
        or lower(dataset) like '%commentaryservicer%'
        or lower(dataset) like '%commentary%' then 'cmbs'
    when lower(dataset) like '%cre%'
        or lower(dataset) like '%microsoft%'
        or lower(dataset) like '%enriched%'
        or lower(dataset) like '%highway_network%'
        or lower(dataset) like '%bk_nod%'
        or lower(dataset) like '%national_highway_data%'
        or lower(dataset) like '%block_data%'
        or lower(dataset) like '%master%' then 'cre'
    when lower(dataset) like '%clo%' then 'clo'
    when lower(dataset) like '%treppwire%' then 'content'
    when lower(dataset) like '%lifecomps%'
        or lower(dataset) like '%treppi%' then 'msd'
    when lower(dataset) like '%banknavigator%'
        or lower(dataset) like '%trepp_survey%'
        or lower(dataset) like '%naic%'
        or lower(dataset) like '%compendium%' then 'lending'
    when lower(dataset) like '%tallr%' then 'tallr'
    when lower(dataset) like '%cherre%'
        or lower(dataset) like '%bls%'
        or lower(dataset) like '%bea%'
        or lower(dataset) like '%wordpress%'
        or lower(dataset) like '%compstak%'
        or lower(dataset) like '%rss%'
        or lower(dataset) like '%compstack%'
        or lower(dataset) like '%american%'
        or lower(dataset) like '%blackknight%'
        or lower(dataset) like '%census%'
        or lower(dataset) like '%attom%'
        or lower(dataset) like '%msamapping%'
        or lower(dataset) like '%uscounty%'
        or lower(dataset) like '%msarank%'
        or lower(dataset) like '%override_data%' then 'platform'
    when lower(dataset) like '%pricing%' then 'pricing'
    when lower(dataset) like '%spatial%' then 'spatial'
    when lower(dataset) like '%datascience%'
    or lower(dataset) like '%dashboardinsights%'
    or lower(dataset) like '%tenantsdashboard%' then 'datascience'
    else 'NA' end as lob,
    concat(date_format(parse_datetime(d.date, 'yyyy-MM-dd'), '%Y'), '-', substr(date_format(parse_datetime(d.date, 'yyyy-MM-dd'), '%M'), 1,3)) as month
from {curation_db}.datasetmetrics d
)
select zone, dataset as dataset_path, domain as prefix, lob, size, primarykey, processmonth, date, month from cte where row_number = 1